name: Deploy Allure report

on:
    push:
        branches: ["develop"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2
            - uses: logikal-io/install-chrome@v1
              with:
                  version: 113.0.5672.126-1
            - uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"
                  cache: maven

            - name: Set up Maven
              uses: stCarolas/setup-maven@v4.5
              with:
                  maven-version: 3.9.1

            - name: Environment variables
              run: echo "${{ secrets.ENV_FILE }}" > .env

            - name: Build with Maven
              run: |
                  mvn -B package --file pom.xml -Dheadless="true"
                  mvn allure:report
              continue-on-error: true

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v1.0.8
              with:
                  path: target/site/allure-maven-plugin
                  retention-days: 10

    deploy:
        needs: build

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
